# Generated by Django 4.1.6 on 2023-02-13 10:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=225)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
    ]
